// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_4xye44fakbcw62datewuskqrwq/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_4xye44fakbcw62datewuskqrwq/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.7_ioredis@5.4.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_4xye44fakbcw62datewuskqrwq/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nitro/server/robots-txt').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_t_773wmu3cukimatof5gt2c7xx24/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@6.1.5_h3@1.13.0_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_t_773wmu3cukimatof5gt2c7xx24/node_modules/@nuxtjs/sitemap/dist/runtime/nitro/routes/sitemap.xml').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nitro/routes/font').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nitro/routes/image').default>>>>
    }
  }
}
export {}