// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.7.0_magicast@0.3.5_rollup@4.26.0_typescript@5.6.3_vue@3.5.12_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5._dfe62jjz2hbvqhty2rsh4hrdbi/node_modules/nuxt-site-config/dist/runtime/nuxt/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.7.0_magicast@0.3.5_rollup@4.26.0_typescript@5.6.3_vue@3.5.12_typescript@5.6.3__webpack-sources@3.2.3/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@primevue+nuxt-module@4.2.1_@babel+parser@7.26.2_magicast@0.3.5_rollup@4.26.0_vue@3.5.12_type_zywj7352laiiisvok3wkungc6q/node_modules/@primevue/nuxt-module/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.23_h3@1.13.0_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_fwu3s2mvqxnao2azsikd6pg5p4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/titles.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser_5rj7kvbgykbfm6dlje3tosmjt4/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser_5rj7kvbgykbfm6dlje3tosmjt4/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/inferSeoMetaPlugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@3.4.2_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_yexp425e367c6m72psoribrspa/node_modules/nuxt-schema-org/dist/runtime/nuxt/plugin/defaults.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-schema-org@3.4.2_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_yexp425e367c6m72psoribrspa/node_modules/nuxt-schema-org/dist/runtime/nuxt/plugin/init.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/og-image-canonical-urls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/plugins/route-rule-og-image.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nuxt/plugins/robot-meta.server.js")> &
  InjectionType<typeof import("../../plugins/i18n")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser_5rj7kvbgykbfm6dlje3tosmjt4/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/1.absoluteImageUrls.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-seo-experiments@4.0.1_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser_5rj7kvbgykbfm6dlje3tosmjt4/node_modules/nuxt-seo-experiments/dist/runtime/nuxt/plugins/0.routeRules.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+seo@2.0.0-rc.23_h3@1.13.0_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_fwu3s2mvqxnao2azsikd6pg5p4/node_modules/@nuxtjs/seo/dist/runtime/nuxt/plugin/defaults.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt-seo:fallback-titles' | 'nuxt-schema-org:defaults' | 'nuxt-schema-org:init' | 'nuxt-seo:defaults'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
