// Generated by nuxt-schema-org

declare module '@nuxt/schema' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@3.4.2_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_yexp425e367c6m72psoribrspa/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}
declare module '#app' {
  export interface RuntimeNuxtHooks {
    'schema-org:meta': (meta: import('../../node_modules/.pnpm/nuxt-schema-org@3.4.2_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_yexp425e367c6m72psoribrspa/node_modules/nuxt-schema-org/dist/runtime/types').MetaInput) => void | Promise<void>
  }
}

export {}
