
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'SectionCourses': typeof import("../components/pages/index/Courses.vue")['default']
    'SectionHeroSliders': typeof import("../components/pages/index/HeroSliders.vue")['default']
    'SectionModels': typeof import("../components/pages/index/Models.vue")['default']
    'SectionSpecialOffers': typeof import("../components/pages/index/SpecialOffers.vue")['default']
    'SectionBar': typeof import("../components/pages/models/model/index/Bar.vue")['default']
    'SectionBriefSection': typeof import("../components/pages/models/model/index/BriefSection.vue")['default']
    'SectionModelHero': typeof import("../components/pages/models/model/index/ModelHero.vue")['default']
    'SectionThreeSixty': typeof import("../components/pages/models/model/index/ThreeSixty.vue")['default']
    'SectionPricingBanner': typeof import("../components/pages/models/model/pricing/PricingBanner.vue")['default']
    'SectionPricingDetailedProperties': typeof import("../components/pages/models/model/pricing/PricingDetailedProperties.vue")['default']
    'SectionPricingFilterSidebar': typeof import("../components/pages/models/model/pricing/PricingFilterSidebar.vue")['default']
    'UIBreadcrumb': typeof import("../components/common/Breadcrumb.vue")['default']
    'UIButton': typeof import("../components/common/Button.vue")['default']
    'UIButtonCarousel': typeof import("../components/common/ButtonCarousel.vue")['default']
    'UIDropdownInput': typeof import("../components/common/DropdownInput.vue")['default']
    'UISection': typeof import("../components/common/Section.vue")['default']
    'UISlideView': typeof import("../components/common/SlideView.vue")['default']
    'UITabsContainer': typeof import("../components/common/TabsContainer.vue")['default']
    'UIFloatingContactButton': typeof import("../components/home/FloatingContactButton.vue")['default']
    'UIBreadCrumbsTickToRight': typeof import("../components/icons/20x20/BreadCrumbsTickToRight.vue")['default']
    'UIFilterIcon': typeof import("../components/icons/20x20/FilterIcon.vue")['default']
    'UIInfoIcon': typeof import("../components/icons/20x20/InfoIcon.vue")['default']
    'UIMoreIcon': typeof import("../components/icons/20x20/MoreIcon.vue")['default']
    'UITickToBottom': typeof import("../components/icons/20x20/TickToBottom.vue")['default']
    'UITickToLeft': typeof import("../components/icons/20x20/TickToLeft.vue")['default']
    'UITickToRight': typeof import("../components/icons/20x20/TickToRight.vue")['default']
    'UITickToTop': typeof import("../components/icons/20x20/TickToTop.vue")['default']
    'UIAnimatedBurgerMenuIcon': typeof import("../components/icons/AnimatedBurgerMenuIcon.vue")['default']
    'UIBurgerMenuIcon': typeof import("../components/icons/BurgerMenuIcon.vue")['default']
    'UICarouselNextIcon': typeof import("../components/icons/CarouselNextIcon.vue")['default']
    'UICarouselPrevIcon': typeof import("../components/icons/CarouselPrevIcon.vue")['default']
    'UICheckIcon': typeof import("../components/icons/CheckIcon.vue")['default']
    'UIElectroCarIcon': typeof import("../components/icons/ElectroCarIcon.vue")['default']
    'UIGlobeIcon': typeof import("../components/icons/GlobeIcon.vue")['default']
    'UIHeartIcon': typeof import("../components/icons/HeartIcon.vue")['default']
    'UIIcon360': typeof import("../components/icons/Icon360.vue")['default']
    'UILenseIcon': typeof import("../components/icons/LenseIcon.vue")['default']
    'UIPhoneIcon': typeof import("../components/icons/PhoneIcon.vue")['default']
    'UIPlayIcon': typeof import("../components/icons/PlayIcon.vue")['default']
    'UIPlayIcon2': typeof import("../components/icons/PlayIcon2.vue")['default']
    'UIServiceRegistrationIcon': typeof import("../components/icons/ServiceRegistrationIcon.vue")['default']
    'UIUserIcon': typeof import("../components/icons/UserIcon.vue")['default']
    'UIXIcon': typeof import("../components/icons/XIcon.vue")['default']
    'UIComputerIcon': typeof import("../components/icons/onboard/ComputerIcon.vue")['default']
    'UIMultimediaIcon': typeof import("../components/icons/onboard/MultimediaIcon.vue")['default']
    'UISalonIcon': typeof import("../components/icons/onboard/SalonIcon.vue")['default']
    'UIFacebookIcon': typeof import("../components/icons/socials/FacebookIcon.vue")['default']
    'UIInstagramIcon': typeof import("../components/icons/socials/InstagramIcon.vue")['default']
    'UITelegramIcon': typeof import("../components/icons/socials/TelegramIcon.vue")['default']
    'UITiktokIcon': typeof import("../components/icons/socials/TiktokIcon.vue")['default']
    'UIYoutubeIcon': typeof import("../components/icons/socials/YoutubeIcon.vue")['default']
    'UIContainer': typeof import("../components/layout/Container.vue")['default']
    'UIDesktopOnly': typeof import("../components/layout/DesktopOnly.vue")['default']
    'UIFooter': typeof import("../components/layout/Footer.vue")['default']
    'UIHeader': typeof import("../components/layout/Header.vue")['default']
    'UISafeAreaView': typeof import("../components/layout/SafeAreaView.vue")['default']
    'UIHeaderMenu': typeof import("../components/layout/header/HeaderMenu.vue")['default']
    'UIHeaderMenuExtended': typeof import("../components/layout/header/HeaderMenuExtended.vue")['default']
    'UILanguageSelector': typeof import("../components/layout/header/LanguageSelector.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'SiteLink': typeof import("../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5._dfe62jjz2hbvqhty2rsh4hrdbi/node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'RobotMeta': typeof import("../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'OgImage': typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'OgImageScreenshot': typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'SchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'SchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'SchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'SchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'SchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'SchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'SchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'SchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'SchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'SchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'SchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'SchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'SchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'PrimeCheckbox': typeof import("primevue/checkbox")['default']
    'PrimeRadioButton': typeof import("primevue/radiobutton")['default']
    'PrimeAccordion': typeof import("primevue/accordion")['default']
    'PrimeAccordionPanel': typeof import("primevue/accordionpanel")['default']
    'PrimeAccordionHeader': typeof import("primevue/accordionheader")['default']
    'PrimeAccordionContent': typeof import("primevue/accordioncontent")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazySectionCourses': typeof import("../components/pages/index/Courses.vue")['default']
    'LazySectionHeroSliders': typeof import("../components/pages/index/HeroSliders.vue")['default']
    'LazySectionModels': typeof import("../components/pages/index/Models.vue")['default']
    'LazySectionSpecialOffers': typeof import("../components/pages/index/SpecialOffers.vue")['default']
    'LazySectionBar': typeof import("../components/pages/models/model/index/Bar.vue")['default']
    'LazySectionBriefSection': typeof import("../components/pages/models/model/index/BriefSection.vue")['default']
    'LazySectionModelHero': typeof import("../components/pages/models/model/index/ModelHero.vue")['default']
    'LazySectionThreeSixty': typeof import("../components/pages/models/model/index/ThreeSixty.vue")['default']
    'LazySectionPricingBanner': typeof import("../components/pages/models/model/pricing/PricingBanner.vue")['default']
    'LazySectionPricingDetailedProperties': typeof import("../components/pages/models/model/pricing/PricingDetailedProperties.vue")['default']
    'LazySectionPricingFilterSidebar': typeof import("../components/pages/models/model/pricing/PricingFilterSidebar.vue")['default']
    'LazyUIBreadcrumb': typeof import("../components/common/Breadcrumb.vue")['default']
    'LazyUIButton': typeof import("../components/common/Button.vue")['default']
    'LazyUIButtonCarousel': typeof import("../components/common/ButtonCarousel.vue")['default']
    'LazyUIDropdownInput': typeof import("../components/common/DropdownInput.vue")['default']
    'LazyUISection': typeof import("../components/common/Section.vue")['default']
    'LazyUISlideView': typeof import("../components/common/SlideView.vue")['default']
    'LazyUITabsContainer': typeof import("../components/common/TabsContainer.vue")['default']
    'LazyUIFloatingContactButton': typeof import("../components/home/FloatingContactButton.vue")['default']
    'LazyUIBreadCrumbsTickToRight': typeof import("../components/icons/20x20/BreadCrumbsTickToRight.vue")['default']
    'LazyUIFilterIcon': typeof import("../components/icons/20x20/FilterIcon.vue")['default']
    'LazyUIInfoIcon': typeof import("../components/icons/20x20/InfoIcon.vue")['default']
    'LazyUIMoreIcon': typeof import("../components/icons/20x20/MoreIcon.vue")['default']
    'LazyUITickToBottom': typeof import("../components/icons/20x20/TickToBottom.vue")['default']
    'LazyUITickToLeft': typeof import("../components/icons/20x20/TickToLeft.vue")['default']
    'LazyUITickToRight': typeof import("../components/icons/20x20/TickToRight.vue")['default']
    'LazyUITickToTop': typeof import("../components/icons/20x20/TickToTop.vue")['default']
    'LazyUIAnimatedBurgerMenuIcon': typeof import("../components/icons/AnimatedBurgerMenuIcon.vue")['default']
    'LazyUIBurgerMenuIcon': typeof import("../components/icons/BurgerMenuIcon.vue")['default']
    'LazyUICarouselNextIcon': typeof import("../components/icons/CarouselNextIcon.vue")['default']
    'LazyUICarouselPrevIcon': typeof import("../components/icons/CarouselPrevIcon.vue")['default']
    'LazyUICheckIcon': typeof import("../components/icons/CheckIcon.vue")['default']
    'LazyUIElectroCarIcon': typeof import("../components/icons/ElectroCarIcon.vue")['default']
    'LazyUIGlobeIcon': typeof import("../components/icons/GlobeIcon.vue")['default']
    'LazyUIHeartIcon': typeof import("../components/icons/HeartIcon.vue")['default']
    'LazyUIIcon360': typeof import("../components/icons/Icon360.vue")['default']
    'LazyUILenseIcon': typeof import("../components/icons/LenseIcon.vue")['default']
    'LazyUIPhoneIcon': typeof import("../components/icons/PhoneIcon.vue")['default']
    'LazyUIPlayIcon': typeof import("../components/icons/PlayIcon.vue")['default']
    'LazyUIPlayIcon2': typeof import("../components/icons/PlayIcon2.vue")['default']
    'LazyUIServiceRegistrationIcon': typeof import("../components/icons/ServiceRegistrationIcon.vue")['default']
    'LazyUIUserIcon': typeof import("../components/icons/UserIcon.vue")['default']
    'LazyUIXIcon': typeof import("../components/icons/XIcon.vue")['default']
    'LazyUIComputerIcon': typeof import("../components/icons/onboard/ComputerIcon.vue")['default']
    'LazyUIMultimediaIcon': typeof import("../components/icons/onboard/MultimediaIcon.vue")['default']
    'LazyUISalonIcon': typeof import("../components/icons/onboard/SalonIcon.vue")['default']
    'LazyUIFacebookIcon': typeof import("../components/icons/socials/FacebookIcon.vue")['default']
    'LazyUIInstagramIcon': typeof import("../components/icons/socials/InstagramIcon.vue")['default']
    'LazyUITelegramIcon': typeof import("../components/icons/socials/TelegramIcon.vue")['default']
    'LazyUITiktokIcon': typeof import("../components/icons/socials/TiktokIcon.vue")['default']
    'LazyUIYoutubeIcon': typeof import("../components/icons/socials/YoutubeIcon.vue")['default']
    'LazyUIContainer': typeof import("../components/layout/Container.vue")['default']
    'LazyUIDesktopOnly': typeof import("../components/layout/DesktopOnly.vue")['default']
    'LazyUIFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyUIHeader': typeof import("../components/layout/Header.vue")['default']
    'LazyUISafeAreaView': typeof import("../components/layout/SafeAreaView.vue")['default']
    'LazyUIHeaderMenu': typeof import("../components/layout/header/HeaderMenu.vue")['default']
    'LazyUIHeaderMenuExtended': typeof import("../components/layout/header/HeaderMenuExtended.vue")['default']
    'LazyUILanguageSelector': typeof import("../components/layout/header/LanguageSelector.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazySiteLink': typeof import("../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5._dfe62jjz2hbvqhty2rsh4hrdbi/node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
    'LazyRobotMeta': typeof import("../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
    'LazyOgImage': typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
    'LazyOgImageScreenshot': typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
    'LazySchemaOrgDebug': typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
    'LazySchemaOrgArticle': typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
    'LazySchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
    'LazySchemaOrgComment': typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
    'LazySchemaOrgEvent': typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
    'LazySchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
    'LazySchemaOrgHowTo': typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
    'LazySchemaOrgImage': typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
    'LazySchemaOrgJobPosting': typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
    'LazySchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
    'LazySchemaOrgOrganization': typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
    'LazySchemaOrgPerson': typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
    'LazySchemaOrgProduct': typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
    'LazySchemaOrgQuestion': typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
    'LazySchemaOrgRecipe': typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
    'LazySchemaOrgReview': typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
    'LazySchemaOrgVideo': typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
    'LazySchemaOrgWebPage': typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
    'LazySchemaOrgWebSite': typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
    'LazySchemaOrgMovie': typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
    'LazySchemaOrgCourse': typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
    'LazySchemaOrgItemList': typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
    'LazySchemaOrgBook': typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
    'LazySchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
    'LazyPrimeCheckbox': typeof import("primevue/checkbox")['default']
    'LazyPrimeRadioButton': typeof import("primevue/radiobutton")['default']
    'LazyPrimeAccordion': typeof import("primevue/accordion")['default']
    'LazyPrimeAccordionPanel': typeof import("primevue/accordionpanel")['default']
    'LazyPrimeAccordionHeader': typeof import("primevue/accordionheader")['default']
    'LazyPrimeAccordionContent': typeof import("primevue/accordioncontent")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const SectionCourses: typeof import("../components/pages/index/Courses.vue")['default']
export const SectionHeroSliders: typeof import("../components/pages/index/HeroSliders.vue")['default']
export const SectionModels: typeof import("../components/pages/index/Models.vue")['default']
export const SectionSpecialOffers: typeof import("../components/pages/index/SpecialOffers.vue")['default']
export const SectionBar: typeof import("../components/pages/models/model/index/Bar.vue")['default']
export const SectionBriefSection: typeof import("../components/pages/models/model/index/BriefSection.vue")['default']
export const SectionModelHero: typeof import("../components/pages/models/model/index/ModelHero.vue")['default']
export const SectionThreeSixty: typeof import("../components/pages/models/model/index/ThreeSixty.vue")['default']
export const SectionPricingBanner: typeof import("../components/pages/models/model/pricing/PricingBanner.vue")['default']
export const SectionPricingDetailedProperties: typeof import("../components/pages/models/model/pricing/PricingDetailedProperties.vue")['default']
export const SectionPricingFilterSidebar: typeof import("../components/pages/models/model/pricing/PricingFilterSidebar.vue")['default']
export const UIBreadcrumb: typeof import("../components/common/Breadcrumb.vue")['default']
export const UIButton: typeof import("../components/common/Button.vue")['default']
export const UIButtonCarousel: typeof import("../components/common/ButtonCarousel.vue")['default']
export const UIDropdownInput: typeof import("../components/common/DropdownInput.vue")['default']
export const UISection: typeof import("../components/common/Section.vue")['default']
export const UISlideView: typeof import("../components/common/SlideView.vue")['default']
export const UITabsContainer: typeof import("../components/common/TabsContainer.vue")['default']
export const UIFloatingContactButton: typeof import("../components/home/FloatingContactButton.vue")['default']
export const UIBreadCrumbsTickToRight: typeof import("../components/icons/20x20/BreadCrumbsTickToRight.vue")['default']
export const UIFilterIcon: typeof import("../components/icons/20x20/FilterIcon.vue")['default']
export const UIInfoIcon: typeof import("../components/icons/20x20/InfoIcon.vue")['default']
export const UIMoreIcon: typeof import("../components/icons/20x20/MoreIcon.vue")['default']
export const UITickToBottom: typeof import("../components/icons/20x20/TickToBottom.vue")['default']
export const UITickToLeft: typeof import("../components/icons/20x20/TickToLeft.vue")['default']
export const UITickToRight: typeof import("../components/icons/20x20/TickToRight.vue")['default']
export const UITickToTop: typeof import("../components/icons/20x20/TickToTop.vue")['default']
export const UIAnimatedBurgerMenuIcon: typeof import("../components/icons/AnimatedBurgerMenuIcon.vue")['default']
export const UIBurgerMenuIcon: typeof import("../components/icons/BurgerMenuIcon.vue")['default']
export const UICarouselNextIcon: typeof import("../components/icons/CarouselNextIcon.vue")['default']
export const UICarouselPrevIcon: typeof import("../components/icons/CarouselPrevIcon.vue")['default']
export const UICheckIcon: typeof import("../components/icons/CheckIcon.vue")['default']
export const UIElectroCarIcon: typeof import("../components/icons/ElectroCarIcon.vue")['default']
export const UIGlobeIcon: typeof import("../components/icons/GlobeIcon.vue")['default']
export const UIHeartIcon: typeof import("../components/icons/HeartIcon.vue")['default']
export const UIIcon360: typeof import("../components/icons/Icon360.vue")['default']
export const UILenseIcon: typeof import("../components/icons/LenseIcon.vue")['default']
export const UIPhoneIcon: typeof import("../components/icons/PhoneIcon.vue")['default']
export const UIPlayIcon: typeof import("../components/icons/PlayIcon.vue")['default']
export const UIPlayIcon2: typeof import("../components/icons/PlayIcon2.vue")['default']
export const UIServiceRegistrationIcon: typeof import("../components/icons/ServiceRegistrationIcon.vue")['default']
export const UIUserIcon: typeof import("../components/icons/UserIcon.vue")['default']
export const UIXIcon: typeof import("../components/icons/XIcon.vue")['default']
export const UIComputerIcon: typeof import("../components/icons/onboard/ComputerIcon.vue")['default']
export const UIMultimediaIcon: typeof import("../components/icons/onboard/MultimediaIcon.vue")['default']
export const UISalonIcon: typeof import("../components/icons/onboard/SalonIcon.vue")['default']
export const UIFacebookIcon: typeof import("../components/icons/socials/FacebookIcon.vue")['default']
export const UIInstagramIcon: typeof import("../components/icons/socials/InstagramIcon.vue")['default']
export const UITelegramIcon: typeof import("../components/icons/socials/TelegramIcon.vue")['default']
export const UITiktokIcon: typeof import("../components/icons/socials/TiktokIcon.vue")['default']
export const UIYoutubeIcon: typeof import("../components/icons/socials/YoutubeIcon.vue")['default']
export const UIContainer: typeof import("../components/layout/Container.vue")['default']
export const UIDesktopOnly: typeof import("../components/layout/DesktopOnly.vue")['default']
export const UIFooter: typeof import("../components/layout/Footer.vue")['default']
export const UIHeader: typeof import("../components/layout/Header.vue")['default']
export const UISafeAreaView: typeof import("../components/layout/SafeAreaView.vue")['default']
export const UIHeaderMenu: typeof import("../components/layout/header/HeaderMenu.vue")['default']
export const UIHeaderMenuExtended: typeof import("../components/layout/header/HeaderMenuExtended.vue")['default']
export const UILanguageSelector: typeof import("../components/layout/header/LanguageSelector.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const SiteLink: typeof import("../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5._dfe62jjz2hbvqhty2rsh4hrdbi/node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const RobotMeta: typeof import("../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const OgImage: typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const OgImageScreenshot: typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const PrimeCheckbox: typeof import("primevue/checkbox")['default']
export const PrimeRadioButton: typeof import("primevue/radiobutton")['default']
export const PrimeAccordion: typeof import("primevue/accordion")['default']
export const PrimeAccordionPanel: typeof import("primevue/accordionpanel")['default']
export const PrimeAccordionHeader: typeof import("primevue/accordionheader")['default']
export const PrimeAccordionContent: typeof import("primevue/accordioncontent")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazySectionCourses: typeof import("../components/pages/index/Courses.vue")['default']
export const LazySectionHeroSliders: typeof import("../components/pages/index/HeroSliders.vue")['default']
export const LazySectionModels: typeof import("../components/pages/index/Models.vue")['default']
export const LazySectionSpecialOffers: typeof import("../components/pages/index/SpecialOffers.vue")['default']
export const LazySectionBar: typeof import("../components/pages/models/model/index/Bar.vue")['default']
export const LazySectionBriefSection: typeof import("../components/pages/models/model/index/BriefSection.vue")['default']
export const LazySectionModelHero: typeof import("../components/pages/models/model/index/ModelHero.vue")['default']
export const LazySectionThreeSixty: typeof import("../components/pages/models/model/index/ThreeSixty.vue")['default']
export const LazySectionPricingBanner: typeof import("../components/pages/models/model/pricing/PricingBanner.vue")['default']
export const LazySectionPricingDetailedProperties: typeof import("../components/pages/models/model/pricing/PricingDetailedProperties.vue")['default']
export const LazySectionPricingFilterSidebar: typeof import("../components/pages/models/model/pricing/PricingFilterSidebar.vue")['default']
export const LazyUIBreadcrumb: typeof import("../components/common/Breadcrumb.vue")['default']
export const LazyUIButton: typeof import("../components/common/Button.vue")['default']
export const LazyUIButtonCarousel: typeof import("../components/common/ButtonCarousel.vue")['default']
export const LazyUIDropdownInput: typeof import("../components/common/DropdownInput.vue")['default']
export const LazyUISection: typeof import("../components/common/Section.vue")['default']
export const LazyUISlideView: typeof import("../components/common/SlideView.vue")['default']
export const LazyUITabsContainer: typeof import("../components/common/TabsContainer.vue")['default']
export const LazyUIFloatingContactButton: typeof import("../components/home/FloatingContactButton.vue")['default']
export const LazyUIBreadCrumbsTickToRight: typeof import("../components/icons/20x20/BreadCrumbsTickToRight.vue")['default']
export const LazyUIFilterIcon: typeof import("../components/icons/20x20/FilterIcon.vue")['default']
export const LazyUIInfoIcon: typeof import("../components/icons/20x20/InfoIcon.vue")['default']
export const LazyUIMoreIcon: typeof import("../components/icons/20x20/MoreIcon.vue")['default']
export const LazyUITickToBottom: typeof import("../components/icons/20x20/TickToBottom.vue")['default']
export const LazyUITickToLeft: typeof import("../components/icons/20x20/TickToLeft.vue")['default']
export const LazyUITickToRight: typeof import("../components/icons/20x20/TickToRight.vue")['default']
export const LazyUITickToTop: typeof import("../components/icons/20x20/TickToTop.vue")['default']
export const LazyUIAnimatedBurgerMenuIcon: typeof import("../components/icons/AnimatedBurgerMenuIcon.vue")['default']
export const LazyUIBurgerMenuIcon: typeof import("../components/icons/BurgerMenuIcon.vue")['default']
export const LazyUICarouselNextIcon: typeof import("../components/icons/CarouselNextIcon.vue")['default']
export const LazyUICarouselPrevIcon: typeof import("../components/icons/CarouselPrevIcon.vue")['default']
export const LazyUICheckIcon: typeof import("../components/icons/CheckIcon.vue")['default']
export const LazyUIElectroCarIcon: typeof import("../components/icons/ElectroCarIcon.vue")['default']
export const LazyUIGlobeIcon: typeof import("../components/icons/GlobeIcon.vue")['default']
export const LazyUIHeartIcon: typeof import("../components/icons/HeartIcon.vue")['default']
export const LazyUIIcon360: typeof import("../components/icons/Icon360.vue")['default']
export const LazyUILenseIcon: typeof import("../components/icons/LenseIcon.vue")['default']
export const LazyUIPhoneIcon: typeof import("../components/icons/PhoneIcon.vue")['default']
export const LazyUIPlayIcon: typeof import("../components/icons/PlayIcon.vue")['default']
export const LazyUIPlayIcon2: typeof import("../components/icons/PlayIcon2.vue")['default']
export const LazyUIServiceRegistrationIcon: typeof import("../components/icons/ServiceRegistrationIcon.vue")['default']
export const LazyUIUserIcon: typeof import("../components/icons/UserIcon.vue")['default']
export const LazyUIXIcon: typeof import("../components/icons/XIcon.vue")['default']
export const LazyUIComputerIcon: typeof import("../components/icons/onboard/ComputerIcon.vue")['default']
export const LazyUIMultimediaIcon: typeof import("../components/icons/onboard/MultimediaIcon.vue")['default']
export const LazyUISalonIcon: typeof import("../components/icons/onboard/SalonIcon.vue")['default']
export const LazyUIFacebookIcon: typeof import("../components/icons/socials/FacebookIcon.vue")['default']
export const LazyUIInstagramIcon: typeof import("../components/icons/socials/InstagramIcon.vue")['default']
export const LazyUITelegramIcon: typeof import("../components/icons/socials/TelegramIcon.vue")['default']
export const LazyUITiktokIcon: typeof import("../components/icons/socials/TiktokIcon.vue")['default']
export const LazyUIYoutubeIcon: typeof import("../components/icons/socials/YoutubeIcon.vue")['default']
export const LazyUIContainer: typeof import("../components/layout/Container.vue")['default']
export const LazyUIDesktopOnly: typeof import("../components/layout/DesktopOnly.vue")['default']
export const LazyUIFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyUIHeader: typeof import("../components/layout/Header.vue")['default']
export const LazyUISafeAreaView: typeof import("../components/layout/SafeAreaView.vue")['default']
export const LazyUIHeaderMenu: typeof import("../components/layout/header/HeaderMenu.vue")['default']
export const LazyUIHeaderMenuExtended: typeof import("../components/layout/header/HeaderMenuExtended.vue")['default']
export const LazyUILanguageSelector: typeof import("../components/layout/header/LanguageSelector.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazySiteLink: typeof import("../node_modules/.pnpm/nuxt-site-config@2.2.21_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5._dfe62jjz2hbvqhty2rsh4hrdbi/node_modules/nuxt-site-config/dist/runtime/nuxt/component/SiteLink.vue")['default']
export const LazyRobotMeta: typeof import("../node_modules/.pnpm/@nuxtjs+robots@4.1.11_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36_dz5z2wmebscxbm5oa3cmiytvhm/node_modules/@nuxtjs/robots/dist/runtime/nuxt/components/RobotMeta")['default']
export const LazyOgImage: typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImage")['default']
export const LazyOgImageScreenshot: typeof import("../node_modules/.pnpm/nuxt-og-image@3.0.8_magicast@0.3.5_rollup@4.26.0_vite@5.4.11_@types+node@22.9.0_terser@5.36.0_zs3lf7utu4nk7htfimc536hosa/node_modules/nuxt-og-image/dist/runtime/nuxt/components/OgImage/OgImageScreenshot")['default']
export const LazySchemaOrgDebug: typeof import("@unhead/schema-org/vue")['SchemaOrgDebug']
export const LazySchemaOrgArticle: typeof import("@unhead/schema-org/vue")['SchemaOrgArticle']
export const LazySchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue")['SchemaOrgBreadcrumb']
export const LazySchemaOrgComment: typeof import("@unhead/schema-org/vue")['SchemaOrgComment']
export const LazySchemaOrgEvent: typeof import("@unhead/schema-org/vue")['SchemaOrgEvent']
export const LazySchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue")['SchemaOrgFoodEstablishment']
export const LazySchemaOrgHowTo: typeof import("@unhead/schema-org/vue")['SchemaOrgHowTo']
export const LazySchemaOrgImage: typeof import("@unhead/schema-org/vue")['SchemaOrgImage']
export const LazySchemaOrgJobPosting: typeof import("@unhead/schema-org/vue")['SchemaOrgJobPosting']
export const LazySchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue")['SchemaOrgLocalBusiness']
export const LazySchemaOrgOrganization: typeof import("@unhead/schema-org/vue")['SchemaOrgOrganization']
export const LazySchemaOrgPerson: typeof import("@unhead/schema-org/vue")['SchemaOrgPerson']
export const LazySchemaOrgProduct: typeof import("@unhead/schema-org/vue")['SchemaOrgProduct']
export const LazySchemaOrgQuestion: typeof import("@unhead/schema-org/vue")['SchemaOrgQuestion']
export const LazySchemaOrgRecipe: typeof import("@unhead/schema-org/vue")['SchemaOrgRecipe']
export const LazySchemaOrgReview: typeof import("@unhead/schema-org/vue")['SchemaOrgReview']
export const LazySchemaOrgVideo: typeof import("@unhead/schema-org/vue")['SchemaOrgVideo']
export const LazySchemaOrgWebPage: typeof import("@unhead/schema-org/vue")['SchemaOrgWebPage']
export const LazySchemaOrgWebSite: typeof import("@unhead/schema-org/vue")['SchemaOrgWebSite']
export const LazySchemaOrgMovie: typeof import("@unhead/schema-org/vue")['SchemaOrgMovie']
export const LazySchemaOrgCourse: typeof import("@unhead/schema-org/vue")['SchemaOrgCourse']
export const LazySchemaOrgItemList: typeof import("@unhead/schema-org/vue")['SchemaOrgItemList']
export const LazySchemaOrgBook: typeof import("@unhead/schema-org/vue")['SchemaOrgBook']
export const LazySchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue")['SchemaOrgSoftwareApp']
export const LazyPrimeCheckbox: typeof import("primevue/checkbox")['default']
export const LazyPrimeRadioButton: typeof import("primevue/radiobutton")['default']
export const LazyPrimeAccordion: typeof import("primevue/accordion")['default']
export const LazyPrimeAccordionPanel: typeof import("primevue/accordionpanel")['default']
export const LazyPrimeAccordionHeader: typeof import("primevue/accordionheader")['default']
export const LazyPrimeAccordionContent: typeof import("primevue/accordioncontent")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_encoding@0.1.13_eslint@9.14.0_jiti@2.4_jmep7dkl7iioarqxya6vnjvzmm/node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
