// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/18/2024, 10:32:38 AM
const configMerger = require("/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.2_magicast@0.3.5_rollup@4.26.0_webpack-sources@3.2.3/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/components/pages//**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/plugins/**/*.{js,ts,mjs}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/composables/**/*.{js,ts,mjs}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/utils/**/*.{js,ts,mjs}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/rakhmatullo/Documents/Github/trigger/kia.uz-frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
