name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Login via SSH and run deploy script
        env:
          SSH_HOST: ${{ secrets.TRIGGER_SSH_HOST }}
          SSH_PORT: ${{ secrets.TRIGGER_SSH_PORT }}
          SSH_USER: ${{ secrets.TRIGGER_SSH_USER }}
          SSH_PASSWORD: ${{ secrets.TRIGGER_SSH_PASSWORD }}
        run: |
          export PNPM_HOME="/home/web/.local/share/pnpm"
          case ":$PATH:" in
            *":$PNPM_HOME:"*) ;;
              *) export PATH="$PNPM_HOME:$PATH" ;;
              esac
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "
            bash -l -c 'cd /home/web/web/kia.triger.uz/public_html && ./deploy.sh'
            "
