name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Copy files via SSH and build on server
      env:
        SSH_HOST: ${{ secrets.TRIGGER_SSH_HOST }}
        SSH_PORT: ${{ secrets.TRIGGER_SSH_PORT }}
        SSH_USER: ${{ secrets.TRIGGER_SSH_USER }}
        SSH_PASSWORD: ${{ secrets.TRIGGER_SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "
          git config --global --add safe.directory /home/web/web/kia.triger.uz/kia.uz-frontend &&
          cd /home/web/web/kia.triger.uz/kia.uz-frontend &&
          git pull origin main &&
          pnpm install &&
          pnpm build &&
          date > /home/web/web/kia.triger.uz/deploy-timestamp.txt &&
          cp -r dist/* /home/web/web/kia.triger.uz/public_html/"
